name: testsharedlib

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  testsharedlib:
    runs-on: ubuntu-latest
    steps:
      - name: sharedlib testing
        uses: ankursrivastva/gitaction5/.github/workflows/docker.yaml@main
